"""five delete rows product id and provider id and replace fk with product_inventories

Revision ID: 38dd235392b0
Revises: f6be8e4616de
Create Date: 2026-07-31 17:45:50.360299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dd235392b0'
down_revision: Union[str, Sequence[str], None] = 'f6be8e4616de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reservation_items_provider_id_fkey'), 'reservation_items', type_='foreignkey')
    op.drop_constraint(op.f('reservation_items_product_id_fkey'), 'reservation_items', type_='foreignkey')
    op.create_foreign_key(None, 'reservation_items', 'product_inventories', ['product_id'], ['id'])
    op.drop_column('reservation_items', 'provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation_items', sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reservation_items', type_='foreignkey')
    op.create_foreign_key(op.f('reservation_items_product_id_fkey'), 'reservation_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('reservation_items_provider_id_fkey'), 'reservation_items', 'inventory_providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###
