"""third migration - add field exires_at on model Otp

Revision ID: 54bea0fba4a8
Revises: 5f53d7244624
Create Date: 2026-07-30 14:46:03.086249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bea0fba4a8'
down_revision: Union[str, Sequence[str], None] = '5f53d7244624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.alter_column('otps', 'otp_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otps', 'otp_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('otps', 'expires_at')
    # ### end Alembic commands ###
