"""eight add sku to order item

Revision ID: 89cce1029dc7
Revises: c3c5518b9673
Create Date: 2026-08-02 01:10:35.282892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89cce1029dc7'
down_revision: Union[str, Sequence[str], None] = 'c3c5518b9673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('sku', sa.String(), nullable=False))
    op.drop_constraint(op.f('order_items_product_inventory_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('orders_reservation_id_fkey'), 'orders', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('orders_reservation_id_fkey'), 'orders', 'reservations', ['reservation_id'], ['id'])
    op.create_foreign_key(op.f('order_items_product_inventory_id_fkey'), 'order_items', 'product_inventories', ['product_inventory_id'], ['id'])
    op.drop_column('order_items', 'sku')
    # ### end Alembic commands ###
