"""seven add version and client idempotency in model reservation

Revision ID: c3c5518b9673
Revises: 5d0c623c369d
Create Date: 2026-08-01 12:56:19.532736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c3c5518b9673"
down_revision: Union[str, Sequence[str], None] = "5d0c623c369d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservations",
        sa.Column("client_idempotency_key", sa.String(length=255), nullable=True),
    )
    op.add_column("reservations", sa.Column("version", sa.Integer(), nullable=True))

    import uuid

    connection = op.get_bind()
    reservations = connection.execute(sa.text("SELECT id FROM reservations")).fetchall()
    for (res_id,) in reservations:
        connection.execute(
            sa.text(
                "UPDATE reservations SET client_idempotency_key = :key, version = 1 WHERE id = :id"
            ),
            {"key": str(uuid.uuid4()), "id": res_id},
        )
    op.alter_column(
        "reservations",
        "client_idempotency_key",
        existing_type=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "reservations", "version", existing_type=sa.Integer(), nullable=False
    )

    op.create_unique_constraint(
        "uq_reservations_client_idempotency_key",
        "reservations",
        ["client_idempotency_key"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_reservations_client_idempotency_key", "reservations", type_="unique"
    )
    op.drop_column("reservations", "version")
    op.drop_column("reservations", "client_idempotency_key")
    # ### end Alembic commands ###
